### ISSUE TITLE
OTPublisher targetElement is not supported

### ISSUE THREAD

**Issue by oojr** [aiham/opentok-react#23]
targetElement is not exposed as a prop, useful to replace dom elements and maintain order

https://tokbox.com/developer/sdks/js/reference/OT.html#initPublisher

**Comment by aiham** [comment]
Hi @oojr, thanks for trying opentok-react. Not exposing targetElement is by design because we've decided to stick with the react-way of doing things as much as possible and that usually involves not manually manipulating the DOM as much as possible. You should consider designing your app to be as declarative as possible and use your components' props and state to ensure the correct order is maintained. If you have a specific example I can point you in the right direction.
